---
Name: taskmanager
After: 'framework/*, cms/*'
---

SilverStripe\CMS\Controllers\ContentController:
    extensions:
        - BucklesHusky\TaskManager\Extension\TaskManagerExtension
    
Page:
    extensions:
        - BucklesHusky\TaskManager\Extension\TaskManagerPageExtension
        
SilverStripe\Security\Member:
    extensions:
        - BucklesHusky\TaskManager\Extension\MemberExt
        
SilverStripe\CMS\Controllers\CMSPageEditController:
    extensions:
        - BucklesHusky\TaskManager\Extension\CMSPageEditControllerExt

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - BucklesHusky\TaskManager\Extension\SiteConfigExtension

SilverStripe\SiteConfig\SiteConfigLeftAndMain:
  extensions:
    - BucklesHusky\TaskManager\Extension\SiteConfigLeftAndMainExtension
