---
Name: taskmanager
After: 'framework/*, cms/*'
---

SilverStripe\CMS\Controllers\ContentController:
    extensions:
        - BucklesHusky\TaskManager\Extension\TaskManagerExtension
    
Page:
    extensions:
        - BucklesHusky\TaskManager\Extension\TaskManagerPageExtension